### ISSUE TITLE
AttributeError: Can't pickle local object 'Stepwise_Additive_Selector.fit.<locals>.worker_func'

### ISSUE THREAD

**Issue by andrewchen527** [tywerbicki/Slater_Lab_SPTB#1]
This is the code producing the issue:
import sys
sys.path.insert(0, '')
import FeatureSelection as fs
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

featureSelection = fs.Stepwise_Additive_Selector()
dfRaw = pd.read_excel("TotalMerged.xlsx", index_col=0)
#Transpose to filter for column names of nominal features
dfRawTranspose = dfRaw.T
#Rename column to "Identifier"
dfRawTranspose = dfRawTranspose.rename(columns={dfRawTranspose.columns[130]: 'Identifier'})
#Create list of nominal feature names
nominal = dfRawTranspose[dfRawTranspose['Identifier'] == 'nominal'].index.to_numpy()
#Get indices of nominal features
nominalList = dfRaw.columns.get_indexer(nominal)

#Remove identifier row
dfRaw.drop(dfRaw.tail(1).index,inplace=True)

#Filter for early term, term and sPTB patients
mask = dfRaw['Group_KH'].isin(['early t', 'term', 'sPTB'])
dfRawSubset = dfRaw[mask]

#Set labels using map
labels = dfRawSubset.loc[:,'Group_KH'].map({"term":0, "sPTB":1, "early t":0}).to_numpy()

#Remove studyid and Group_KH
dfRawSubset = dfRawSubset.iloc[:,2:]

featureSelection.fit(dfRawSubset, labels, nominalList)
# %%

**Comment by tywerbicki** [comment]
Thanks Andrew.

An addition to the library source code was made to rectify this issue. In the fit() method, the worker_func function is now declared as global to support pickling.

Closing issue.
